### ISSUE TITLE
config.get<boolean> return unexpected value

### ISSUE THREAD

**Issue by aquariuslt** [nestjs/config#91]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior

From the documentation
```
@Injectable()
export class ApiConfigService {
  constructor(private configService: ConfigService) {}

  get isAuthEnabled(): boolean {
    return Boolean(this.configService.get('AUTH_ENABLED'));  // if `AUTH_ENABLED=false` in .env it might get true with `Boolean('false')`
  }
}
```

## Expected behavior

when `.env` file contains boolean value
such as

```
DATABASE_SYNC=false
```

and `ConfigModule` options contains Joi Schema validation
like `Joi.boolean().default(false)`.

the `validatedConfig` from joi `validate(config, validateOptions)` will return a boolean value.

// now  typeof validatedConfig['DATABASE_SYNC'] === 'boolean'

after `assignVariablesToProcess`, we can not get boolean value which has been validated and perform expected type cast behavior.

suppose `config.get<boolean>('DATABASE_SYNC')` return same value from validatedConfig?

## Minimal reproduction of the problem with instructions

You might run below unittest code (append test case in `validation-schema.spec.ts`)

```
it(`should validate loaded env with boolean variables`, async () => {
    const withBooleanSchemaValidationModule = (): DynamicModule => {
      return {
        module: AppModule,
        imports: [
          ConfigModule.forRoot({
            validationSchema: Joi.object({
              DATABASE_SYNC: Joi.boolean().default(false),
            }),
          }),
        ],
      };
    };

    const module = await Test.createTestingModule({
      imports: [withBooleanSchemaValidationModule()],
    }).compile();

    app = module.createNestApplication();
    await app.init();
    const config = app.get(ConfigService);

    const isDatabaseSync = config.get<boolean>('DATABASE_SYNC');

    expect(typeof isDatabaseSync).toBe('boolean'); // Received: 'string'
    expect(Boolean(isDatabaseSync)).toBeFalsy(); // Received: true  from `Boolean('false')`

    await app.close();
  });
```

## What is the motivation / use case for changing the behavior?

I want to migrate my application code configuration module to `@nestjs/config`, and found boolean value in `.env` file can not load correctly.

## Environment

<pre><code>
Nest version: 6.11.8

 
For Tooling issues:
- Node version: v12.6.0  
- Platform:  Mac 

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Fixed in 0.2.4

**Comment by AlexisMarchand** [comment]
Sorry but it still doesn't work with me.

```javascript
console.log(this.configService.get('CRON_QUEUE_PAQUET_GO')=="true"); //return false
console.log(this.configService.get('CRON_QUEUE_PAQUET_GO')=="false"); //return true
console.log(this.configService.get<boolean>('CRON_QUEUE_PAQUET_GO')); //return false
console.log(!this.configService.get<boolean>('CRON_QUEUE_PAQUET_GO')); //return false expected true
```

Environment (extract package.json)
...
@nestjs/common": "^6.10.14",
@nestjs/config": "^0.5.0"
...
